services:
  web:
    build: .
    # uncomment the line below if running on linux machine
    # network_mode: host
    ports:
      - "80:8080"
    depends_on:
      db:
        condition: service_healthy
      
  db:
    image: postgres:16.2
    restart: always
    # uncomment the line below if running on linux machine
    # network_mode: host
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U docker -d transactions"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./resources/db/:/docker-entrypoint-initdb.d
