// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// Dao is an autogenerated mock type for the Dao type
type Dao struct {
	mock.Mock
}

// Create provides a mock function with given fields: txn, sourceAccountId, destinationAccountId, amount
func (_m *Dao) Create(txn pgx.Tx, sourceAccountId int64, destinationAccountId int64, amount float64) error {
	ret := _m.Called(txn, sourceAccountId, destinationAccountId, amount)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(pgx.Tx, int64, int64, float64) error); ok {
		r0 = rf(txn, sourceAccountId, destinationAccountId, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDao creates a new instance of Dao. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDao(t interface {
	mock.TestingT
	Cleanup(func())
}) *Dao {
	mock := &Dao{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
